name: CI
on: [push]

jobs:
  build:
    name: ESLint Checks
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "ESLint"
        uses: gimenete/eslint-action@1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
